import React from "react";
import ".././globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading} from '@clerk/nextjs';
import Loader from '@/components/Loader';
// import SessionWrapper from "@/components/SessionWrapper";

export const metadata = {
    title: 'Acm Social App',
    description: 'Generated by Acm',
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
        <html lang='en'>
        <body>
        <ClerkLoading>
       <Loader />
       </ClerkLoading>
       <ClerkLoaded> 
            {children}
        </ClerkLoaded>
       </body>
        </html>
        </ClerkProvider> 
    );
}