import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';
import Loader from '@/components/Loader';
import SessionWrapper from "@/components/SessionWrapper";
import CommentModal from "@/components/CommentModal";
import ClientLayout from "./ClientLayout";



const geistSans = Geist({
  src: "../fonts/Geist/Geist-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  src: "../fonts/Geist_Mono/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Acm Social App",
  description: "Generated by Acm",  
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  colorScheme: 'dark light',
};

export default function RootLayout({ children }) {

  return (    
    <ClerkProvider>
      <SessionWrapper>
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-[56px] sm:pt-0`}
      >
      <ClerkLoading>
       <Loader />
       </ClerkLoading>
       <ClerkLoaded>
        
        <div className='hidden lg:flex justify-between max-w-screen mx-auto'>
                <div className='hidden sm:inline h-screen top-0 flex-col'>
                  <LeftSidebar />
                </div>

                <div className='w-2xl hidden lg:block border-l border-r lg:flex-col'>{children}</div>
                <div className='flex-col p-3 h-screen hidden lg:block w-[24rem]'>
                  <RightSidebar />
                </div>
              </div>
             
        <ClientLayout className='hidden lg:block'>          
          {children}
          </ClientLayout>
          
        <CommentModal />
      
       </ClerkLoaded>
      </body>
    </html>
   </SessionWrapper>
   </ClerkProvider>
  );
}
