import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from '@clerk/nextjs';
import Loader from '@/components/Loader';
// import SessionWrapper from "@/components/SessionWrapper";
// import CommentModal from "@/components/CommentModal";


const geistSans = Geist({
  src: "../fonts/Geist/Geist-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  src: "../fonts/Geist_Mono/GeistMono-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Acm Social App",
  description: "Generated by Acm",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    {/* <SessionWrapper> */}
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ClerkLoading>
       <Loader />
       </ClerkLoading>
       <ClerkLoaded>
        <>
        <div className='flex justify-between max-w-6xl mx-auto'>
          <div className='h-screen border-r top-0 hidden sm:inline sticky'>
            <LeftSidebar />
            </div>

          <div className='w-2xl flex-1'>{children}</div>         
          <div className='lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]'>
            <RightSidebar />
            </div>
        </div>        
        </>
        {/* <CommentModal /> */}
       </ClerkLoaded>
      </body>
    </html>
    {/* </SessionWrapper> */}
    </ClerkProvider>
  );
}
